### PR TITLE
feat:Add support for React 18

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by emilpalsson** [comment]
@ScriptedAlchemy Do you have any plans to create a new release with this?

**Comment by ScriptedAlchemy** [comment]
oh it didnt auto release. Will do tomorrow

**Comment by OliverJAsh** [comment]
@ScriptedAlchemy Do you know when this will be released? Can I do anything to help?

**Comment by jialu98** [comment]
@ScriptedAlchemy Could please release it? The last release is 3.0.0 (2018-07-25)

**Comment by ScriptedAlchemy** [comment]
Sorry will do

**Pull request merged**
