### PR TITLE
feat(requireUniversalModule.js): Always apply options & allow skipping of babelRename

### PR DESCRIPTION
**Pull request by konpikwastaken**
In addModule method, we will now use the 'ignoreBabelRename' to determine if we should skip applying
a regex to the chunk name which is typically determined from the file path (with `/` replaced with `-` characters).  This is not always the case, as dynamic imports can have static strings, and can also reference webpack aliases. This gives the user more control over what they want. Additionally, in the getConfig method, options provided, (e.g. a custom chunkName function), does not get used.

### CODE REVIEW

**Comment by konpikwastaken** [comment]
@faceyspacey Can you please take a look into merging this PR?  The codeclimate fail appears to be negligible as only a single `if` was added.

**Comment by ScriptedAlchemy** [comment]
Please add to the readme and document the change. @konpikwastaken

**Comment by ScriptedAlchemy** [comment]
Will revuew

**Comment by ScriptedAlchemy** [comment]
question, what happens if you set it to true and use the babel plugin something feels incorrect here. Youd have to manually set a chunkname for every dynamic import, correct?

**Comment by konpikwastaken** [comment]
@ScriptedAlchemy No, the default value (which is path of import) would be the chunk name (see [here](https://github.com/faceyspacey/react-universal-component/pull/145/files#diff-379d151a3fa5b71c965f365e7386181dR140)).

Default behavior does not change, and the assumption is that if you **do** ignore the babel rename (set true), you either provide your own naming function or skip the rename altogether.

The actual use case for this is when you have a dynamic import of a path that is aliased, e.g.

```javascript
let mod = import(`aliasPath/${moduleName}`
```

webpack will name this chunk as `aliasPath/src-modules-module-moduleName` and the current babelRename function replaces all `/` with `-`. This gives you more granular control with default behavior for those that don't need this.

**Comment by konpikwastaken** [comment]
Oh, and as a side effect of webpack creating chunk names with a `/` in them (if you choose), it will actually output your chunk names into a named folder so you can group things within different dynamic import contexts.

**Comment by ScriptedAlchemy** [comment]
what if we were to remove the babelrename all together?

So not replace `/` with `-` 

Id like to do it, but i had some issues with the babel plugin and flush chunks. 

dont know if youd be up to the task of debugging it. but id love to get rid of the rename all-together!

**Comment by konpikwastaken** [comment]
I think the rename has to happen, because that's how webpack names the chunks, as mentioned in the other PR, the exception is an aliased path as described above.

**Comment by ScriptedAlchemy** [comment]
Theres other scenarios though. Where slashed chunknames do come up

**Comment by konpikwastaken** [comment]
@ScriptedAlchemy Just following up on this as it's been nearly a month - since this is a non-breaking change and really need this in a current project, could you merge and release a minor 3.x.y version with this? It would be greatly appreciated while we work out the details of the "proper" long term chunk naming solution.

**Comment by ScriptedAlchemy** [comment]
Fair point @konpikwastaken ill merge it

**Pull request merged**
