### PR TITLE
V4.0.0

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**

### CODE REVIEW

**Comment by jaybe78** [comment]
Hey @ScriptedAlchemy
Sorry for the delay, I've been swamped + got distracted by npm issue https://github.com/webpack/webpack/issues/8656

Anyway, I've pulled your branch and used it in my project, all LGTM ! 👍
I've even  upgraded to babel 7, it all works smoothly.
Will do a couple of more test throughout the days.

**Comment by erykpiast** [comment]
Hey @ScriptedAlchemy, where may I find changelog or migration guide for this version? It was major upgrade, so I assume there is some code update reqiuired on my side...?

**Comment by jaybe78** [comment]
@erykpiast The migration is seamless, It works as such. You should not need to change anything in your code.

**Comment by ScriptedAlchemy** [comment]
Yep it’s a clean upgrade. Just the underlying React api is completely new (no more componentWillMount)

**Comment by marnusw** [comment]
@ScriptedAlchemy would you mind just adding a note about it being a clean upgrade in the GitHub Releases section? I was hesitant to upgrade myself until I hunted down this PR.

**Comment by ScriptedAlchemy** [comment]
Will do. Usually rely on the releases section to communicate this. I’ll update it today or tomorrow.

**Pull request merged**
