### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by forabi**

### CODE REVIEW

**Comment by faceyspacey** [comment]
thanks for this!

**Comment by faceyspacey** [comment]
for future reference make sure to use `npm run cm` so that when your PRs are merged, it auto-publishes to NPM.

**Comment by circlingthesun** [comment]
This broke my build. I get the following error:

```
TS2345: Argument of type '(props: any) => Promise<any>' is not assignable to parameter of type '{ load(props: {}): PromiseLike<Module<ComponentType<{}>>>; }'.
  Property 'load' is missing in type '(props: any) => Promise<any>'.
```

for this code:

```
const UniversalComponent = universal(props => System.import(`./${props.page}`), {
	loading: <div className="loader"></div>
})
```

It appears that the 2nd type definition for the `universal` function clobbers the 1st one.

**Comment by circlingthesun** [comment]
Removing the 2nd definition results in another set of TS issues. Reverting back to 2.5.5.

**Comment by faceyspacey** [comment]
@forabi any idea what's going on?

**Pull request merged**
