### PR TITLE
React16 API

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
on npm as `@react16`

This is a breaking change

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
You tell me it’s stable. And I’ll release a flag tonight on NPM for you. Then roll it as a major release in a few days

**Comment by jaybe78** [comment]
@ScriptedAlchemy I'm using it in my project. It is stable

**Comment by ScriptedAlchemy** [comment]
@jaybe78 anything you'd like to PR into it, take a look at the branch and then I'll give it a final brush, merge, and major release. 

@GuillaumeCisco is there any way we can collab on this and make it one major release for both redux 6 and react 17?

**Comment by jaybe78** [comment]
@ScriptedAlchemy Would be nice to upgrade to babel 7 as well as part of that change. I did it in my branch, it's a seamless change: https://github.com/jaybe78/react-universal-component/blob/master/package.json
Other than that il all looks good and ready to be merged.
Thanks

**Comment by GuillaumeCisco** [comment]
@ScriptedAlchemy, thanks for poking into this issue.
As I explained in https://github.com/faceyspacey/react-universal-component/issues/172, we should only document the way users should work with `react-redux@6.0.0` as the redux store will not be available the same way.

**Comment by ScriptedAlchemy** [comment]
Okay, i can merge this, Do you want to open a PR for babel 7? I dont mind moving to that and have done so in some places, this will be a major release

**Comment by jaybe78** [comment]
@ScriptedAlchemy hehe don't worry I will be a pain in the ass until you merge it. I will create PR for babel 7. Thanks :)

**Comment by ScriptedAlchemy** [comment]
Got some build errors I’m addressing, should merge it tomorrow /:

**Comment by ScriptedAlchemy** [comment]
PR opened here. some additional changes need to go in
https://github.com/faceyspacey/react-universal-component/pull/176

**Comment by ScriptedAlchemy** [comment]
`react-universal-component@4.0.0-alpha.4`

**Comment by ScriptedAlchemy** [comment]
@jaybe78 One last time, will you try the released alpha I put up yesterday 

Fixed the build issues so I'm ready to merge

**Comment by jaybe78** [comment]
@ScriptedAlchemy Will check it today, I'll get back to you ASAP. Thanks!

**Comment by ScriptedAlchemy** [comment]
Thanks I’ll merge if ur happy

**Comment by ScriptedAlchemy** [comment]
Merged via another PR which had other various updates

**Pull request closed without merging**
